# These are supported funding model platforms

# github: [ahmadawais]
custom: ['https://Awais.dev/sponsor-USD-10-pm', 'https://Awais.dev/sponsor-USD-10', 'https://Awais.dev/sponsor-USD-100', 'https://Awais.dev/sponsor-USD-50']
